"""
HIT140 Assessment 2 - Task 4: Attacking Threat of Under-30 Forwards
Vivian Vu | Darwin Group 88
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats  

# Question is: Among forwards under 30 at the FIFA World Cup 2026, is the mean number of 
# shots on target per 90 minutes different between pure strikers and forward-midfielders?

print("=" * 62)
print("Among under-30 forwards at the FIFA World Cup 2026, is mean shots on")
print("target per 90 minutes different between pure strikers and")
print("forward-midfielders?")

# Parameters:
#   mu1 = population mean sot90 of pure strikers
#   mu2 = population mean sot90 of forward-midfielders
#
# Hypotheses (no direction was predicted in advance, so this is two-sided):
#   H0: mu1 = mu2
#   Ha: mu1 != mu2
#
# Type of test: two-sample t-test (independent t-test), because we have two
# separate samples drawn from two distinct populations.

ALPHA = 0.05
SEED = 42
N_STRIKER = 48        # sample size drawn from the striker population
N_FWDMID = 32         # sample size drawn from the forward-midfielder population
Z_STAR = 1.960        # z* for a 95% confidence level

print("\n" + "=" * 62)
print("=" * 62)
print("Parameters : mu1 = mean sot90 (Striker), mu2 = mean sot90 (Fwd-Mid)")
print("H0         : mu1 = mu2")
print("Ha         : mu1 != mu2      (two-sided)")
print(f"Test       : two-sample t-test,  alpha = {ALPHA}")

# Load the two populations 
df = pd.read_csv("Forward_u30.csv").dropna(subset=["sot90"])

striker_pop = df[df["group"] == "Striker"]["sot90"]
fwdmid_pop = df[df["group"] == "Forward-Midfielder"]["sot90"]

print("\n" + "=" * 62)
print("=" * 62)
print("\n--- POPULATIONS AND SAMPLES ---")
print(f"Population size N (Striker)          : {len(striker_pop)}")
print(f"Population size N (Forward-Midfielder): {len(fwdmid_pop)}")

# Draw a simple random sample from each population 
# A simple random sample is drawn separately from each of the two populations,
# which is what the two-sample t-test assumes. random_state fixes the draw so the result is reproducible.
striker = striker_pop.sample(n=N_STRIKER, random_state=SEED).values
fwdmid = fwdmid_pop.sample(n=N_FWDMID, random_state=SEED).values

print(f"\nSample size n (Striker)              : {N_STRIKER}")
print(f"Sample size n (Forward-Midfielder)   : {N_FWDMID}")
print("Both samples have n >= 30, so the Central Limit Theorem applies and")
print("the sampling distribution of the mean is approximately normal.")

# Check the conditions for inference
# Condition 1: the samples were generated by a simple random sampling procedure.
# Condition 2: the sample data should be roughly normally distributed. As taught,
#              this is checked visually with a histogram.
print("\n--CONDITIONS FOR INFERENCE---")
print("Condition 1 (simple random sampling) : satisfied by the draw above.")
print("Condition 2 (normality)              : checked visually below.")

fig, axes = plt.subplots(1, 3, figsize=(15, 4.2))

axes[0].hist(striker, bins=10, color="#7B9CC4", edgecolor="black")
axes[0].set_title(f"Striker (n = {N_STRIKER})")
axes[0].set_xlabel("Shots on target per 90")
axes[0].set_ylabel("Number of players")

axes[1].hist(fwdmid, bins=10, color="#F5A04A", edgecolor="black")
axes[1].set_title(f"Forward-Midfielder (n = {N_FWDMID})")
axes[1].set_xlabel("Shots on target per 90")
axes[1].set_ylabel("Number of players")

bp = axes[2].boxplot([striker, fwdmid], patch_artist=True, widths=0.5,
                     tick_labels=["Striker", "Forward-\nMidfielder"])
for patch, c in zip(bp["boxes"], ["#7B9CC4", "#F5A04A"]):
    patch.set_facecolor(c)
    patch.set_edgecolor("black")
axes[2].set_title("Comparison of the two samples")
axes[2].set_ylabel("Shots on target per 90")

plt.tight_layout()
plt.savefig("attacking_threat_distributions.png", dpi=200, bbox_inches="tight")
plt.show()

print("Both histograms are right-skewed rather than symmetric, so we keep in")
print("mind that the p-value of the t-test may be only approximately accurate.")

# Compute the basic statistics 
def compute_descriptive_stats(data, name):
    """Measures of central tendency and dispersion."""
    n = len(data)
    mean_val = np.mean(data)
    median_val = np.median(data)
    s_squared = np.var(data, ddof=1)
    s = np.std(data, ddof=1)
    data_range = np.max(data) - np.min(data)

    q75, q25 = np.percentile(data, [75, 25])
    iqr = q75 - q25

    return {
        "Group": name, "n": n,
        "Mean": mean_val, "Median": median_val,
        "Variance": s_squared, "Std Dev": s,
        "Range": data_range, "IQR": iqr
    }

print("\n--- DESCRIPTIVE STATISTICS ---")
desc_df = pd.DataFrame([
    compute_descriptive_stats(striker, "Striker"),
    compute_descriptive_stats(fwdmid, "Forward-Midfielder")
])
print(desc_df.to_string(index=False))

n1, n2 = len(striker), len(fwdmid)
mean1, mean2 = np.mean(striker), np.mean(fwdmid)
s1, s2 = np.std(striker, ddof=1), np.std(fwdmid, ddof=1)

# Confidence interval estimation
# 95% CI = x-bar  +/-  z* * (s / sqrt(n))
#   s / sqrt(n)          is the standard error
#   z* * (s / sqrt(n))   is the margin of error
# z* = 1.960 for a 95% confidence level, and n >= 30 in both samples.
def compute_ci(mean, s, n):
    standard_error = s / np.sqrt(n)
    margin_of_error = Z_STAR * standard_error
    return mean - margin_of_error, mean + margin_of_error

ci_striker = compute_ci(mean1, s1, n1)
ci_fwdmid = compute_ci(mean2, s2, n2)

print("\n-- 95% CONFIDENCE INTERVALS ---")
print(f"Striker           : [{ci_striker[0]:.4f}, {ci_striker[1]:.4f}]")
print(f"Forward-Midfielder: [{ci_fwdmid[0]:.4f}, {ci_fwdmid[1]:.4f}]")

# Compute the t-statistic
#            (x-bar_1 - x-bar_2)
# t* = ---------------------------------
#      sqrt( s1^2 / n1  +  s2^2 / n2 )
standard_error_diff = np.sqrt((s1 ** 2 / n1) + (s2 ** 2 / n2))
t_star = (mean1 - mean2) / standard_error_diff

# Degrees of freedom: taking the conservative approach, select the smaller of
# the two degrees of freedom (n1 - 1 and n2 - 1).
df_conservative = min(n1 - 1, n2 - 1)

# Compute the p-value
# Two-sided p-value, obtained with software for greater precision than the
# printed t-distribution table.
p_value = stats.t.sf(np.abs(t_star), df_conservative) * 2

print("\n--- TWO-SAMPLE t-TEST ---")
print(f"Mean difference (Striker - Fwd-Mid) : {mean1 - mean2:.4f}")
print(f"Standard error of the difference    : {standard_error_diff:.4f}")
print(f"t-statistic (t*)                    : {t_star:.4f}")
print(f"Degrees of freedom (conservative)   : {df_conservative}")
print(f"p-value (two-sided)                 : {p_value:.4f}")


print("\n" + "=" * 62)
print("=" * 62)
print(f"Reporting (APA): t({df_conservative}) = {t_star:.2f}, p = {p_value:.4f}")

if p_value <= ALPHA:
    print(f"\np-value <= {ALPHA}. There is sufficient statistical evidence to")
    print("reject H0.")
    print("Conclusion: the mean shots on target per 90 differs between pure")
    print("strikers and forward-midfielders.")
else:
    print(f"\np-value > {ALPHA}. There is not enough statistical evidence to")
    print("reject H0.")
    print("Conclusion: we cannot conclude that the mean shots on target per 90")
    print("differs between pure strikers and forward-midfielders.")
    print("\nNote: failing to reject H0 is not the same as proving that the two")
    print("groups are identical. The sample means do differ by "
          f"{mean1 - mean2:.3f}, but this")
    print("difference is not large enough, relative to the variation in the")
    print("data, to rule out ordinary chance variation.")

print("\nLimitation: both samples are right-skewed rather than normal, so the")
print("p-value above should be treated as approximate.")
